packer {
  required_plugins {
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
    vagrant = {
      source  = "github.com/hashicorp/vagrant"
      version = "~> 1"
    }
    virtualbox = {
      source  = "github.com/hashicorp/virtualbox"
      version = "~> 1"
    }
  }
}

variable "version" {
  type    = string
  default = ""
}

source "virtualbox-iso" "autogenerated_1" {
  boot_command            = ["<tab> text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/anaconda-ks.cfg<enter><wait>"]
  // boot_command            = ["<esc><esc>text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/anaconda-ks.cfg<enter><wait>"]
  //boot_command            = ["<tab><up><enter>text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/anaconda-ks.cfg<enter><wait>"]
  boot_wait               = "10s"
  disk_size               = 81920
  guest_additions_path    = "VBoxGuestAdditions_{{ .Version }}.iso"
  guest_os_type           = "RedHat_64"
  headless                = true
  http_port_min           = 8080
  http_port_max           = 8080
  http_directory          = "http"
  iso_checksum            = "sha256:398561d7b66f1a4bf23664f4aa8f2cfbb3641aa2f01a320068e86bd1fc0e9076"
  iso_urls                = ["rhel9_4.iso", "https://andromedabay.ddns.net/d45623_rhel9_4/rhel9_4.iso"]
  shutdown_command        = "echo 'vagrant'|sudo -S /sbin/halt -h -p"
  ssh_password            = "vagrant"
  ssh_port                = 22
  ssh_username            = "vagrant"
  ssh_wait_timeout        = "1800s"
  // vboxmanage              = [["modifyvm", "{{ .Name }}", "--memory", "1536"], ["modifyvm", "{{ .Name }}", "--cpus", "1"]]
  vboxmanage              = [["modifyvm", "{{ .Name }}", "--memory", "2048"], ["modifyvm", "{{ .Name }}", "--cpus", "1"],["modifyvm", "{{.Name}}", "--nat-localhostreachable1", "on"]]
  virtualbox_version_file = ".vbox_version"
  vm_name                 = "packer-rhel-9_4-x86_64"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  // provisioner "shell" {
  //   execute_command = "echo 'vagrant' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
  //   script          = "scripts/ansible.sh"
  // }

  // provisioner "ansible-local" {
  //   galaxy_file   = "../shared/requirements.yml"
  //   playbook_file = "../shared/main.yml"
  // }

  provisioner "shell" {
    execute_command = "echo 'vagrant' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    script          = "scripts/cleanup.sh"
  }

  post-processors {
    post-processor "vagrant" {
      output = "builds/{{ .Provider }}-rhel9_4.box"
    }
    // post-processor "vagrant-cloud" {
    //   box_tag = "raufhammad/rhel9_4"
    //   version = "${var.version}"
    // }
    post-processor "vagrant-registry" {
      box_tag = "raufhammad/rhel9_4"
      version = "${var.version}"
    }    
  }
}
