---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    boxes:
      - rockylinux8
      - centos7
      - ubuntu2004
      - debian12      
    versions: {}

  tasks:

    - include_tasks: shared/build-a-box.yml
      with_items: "{{ boxes }}"
